--- 
- hosts: slave1
  remote_user: root
  become: yes
  tasks:
   - name: install apache2 package
     apt: name=nginx state=present
   - name: copy index.html
     copy: src=/var/www/html/index.html dest=/var/www/html
   - name: start apache2 server
     service: name=apache2 state=started
